// flow-typed signature: d940edaf243a1cd353802596e3720cd6
// flow-typed version: <<STUB>>/to-redux-type_v^1.2.3/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-redux-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-redux-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-redux-type/app' {
  declare module.exports: any;
}

declare module 'to-redux-type/dist/to-redux-type' {
  declare module.exports: any;
}

declare module 'to-redux-type/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-redux-type/app.js' {
  declare module.exports: $Exports<'to-redux-type/app'>;
}
declare module 'to-redux-type/dist/to-redux-type.js' {
  declare module.exports: $Exports<'to-redux-type/dist/to-redux-type'>;
}
declare module 'to-redux-type/src/main.js' {
  declare module.exports: $Exports<'to-redux-type/src/main'>;
}
